acc_figpath: E:\Topici\logs\training_validation_accuracy.png
additional_info: 0.75 M parameters
batch_size: 32
cm_figpath: E:\Topici\logs\confusion_matrix.png
data_figpath: E:\Topici\logs\data_characteristics.png
dataset:
  name: FACED Dataset
  url: https://www.synapse.org/#!Synapse:syn50614194/files
dataset_name: FACEDDataset
describe_dataset: 'For detail information about the dataset, refer to this <a href="https://openneuro.org/datasets/ds003775/versions/1.2.1">link</a>.

  '
describe_overview: 'The model analyzed in this card classifies EEG into abnormal or
  normal class and returns an uncertainty estimation of the

  predicted class with a confidence interval. It reports the model''s hyperparameters
  and performance plots. The reader can gain further

  insights about the model''s limitation by identifying the input instances where
  the model is expected to perform well.

  '
description: A CNN model for EEG signal classification.
ground_truth: Health status (abnormal or normal)
io_path: .torcheeg/datasets_1735593565489_9a9Qv
learning_approach: Supervised
learning_rate: 1e-05
limitation_details:
- The training dataset inherits class imbalance, with a male-to-female ratio of 3:1,
  which could potentially lead to fairness concerns.
- Noisy channels, missing channels in the data will degrade the model's performance.
logo_path: E:\Topici\Dream\download.png
loss_figpath: E:\Topici\logs\training_validation_loss.png
metrics:
- accuracy
- loss
model_details: 'Further details about the model is available <a href="https://openneuro.org/datasets/ds003775/versions/1.2.1">here</a>.

  '
model_input:
- 19-channel EEG data in time domain.
model_name: TSCeption
model_output:
- Classification of the subject as abnormal or normal class.
- Confidence interval of model's performance.
model_type: Convolutional Neural Net
num_target_class: 9
performance_comments: Here you can dig into the model's performance on a selection
  of evaluation datasets drawn from different data sources than the training data.
preprocess_steps: 'Independent Component Analysis, Band Pass Filtering, Normalization.

  '
references: "<ol>\n\n  <li>Mitchell, M., Wu, S., Zaldivar, A., Barnes, P., Vasserman,\
  \ L., Hutchinson, B., Spitzer, E., Raji, I.D. and Gebru, T., 2019, January. Model\
  \ cards for model reporting.\n      In Proceedings of the conference on fairness,\
  \ accountability, and transparency (pp. 220-229)</li>\n  \n  <li>Mitchell, M., Wu,\
  \ S., Zaldivar, A., Barnes, P., Vasserman, L., Hutchinson, B., Spitzer, E., Raji,\
  \ I.D. and Gebru, T., 2019, January. Model cards for model reporting.\n      In\
  \ Proceedings of the conference on fairness, accountability, and transparency (pp.\
  \ 220-229)</li>"
result_table_figpath: E:\Topici\logs\metrics_table.png
split_ratio: '80:20'
uncertainty_describe: 'Confidence intervals provide an additional perspective on the
  uncertainty surrounding the reported metrics

  and performance of the model.

  '
uncertainty_figpath: ./logs/confidence_intervals.png
version: '1.0'
